version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sodanen_bot_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=sodanen_bot
      - DB_USER=root
      - DB_PASSWORD=1234
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    networks:
      - sodanen_network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mariadb:
    image: mariadb:11.1
    container_name: sodanen_bot_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sodanen_bot
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      - ./docker/mariadb/config:/etc/mysql/conf.d
    networks:
      - sodanen_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  nginx:
    image: nginx:alpine
    container_name: sodanen_bot_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./dist:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - sodanen_network

volumes:
  mariadb_data:
    driver: local

networks:
  sodanen_network:
    driver: bridge
